#!/usr/bin/env python3
"""Generate references/civ6-policies-governments-catalog.md from the installed Civ VI data:
all policy cards (by slot) + governments (base + Rise&Fall + Gathering Storm). INSPIRATION corpus
for Civ VII modding — mine Civ VI concepts for ideas, but check feasibility against the Civ VII
mechanic delta + effects catalog first (many Civ VI systems don't exist in Civ VII). Not bundled;
regenerate after install changes. Auto-detects the Civ VI install via $CIV6_ROOT / Steam libraries."""
import os, re, glob, html

def find_civ6_root():
    env = os.environ.get("CIV6_ROOT")
    if env and os.path.isdir(env): return env
    libs = {r"C:\Program Files (x86)\Steam", r"C:\Program Files\Steam"}
    try:
        vdf = open(r"C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf", encoding="utf-8", errors="replace").read()
        for m in re.findall(r'"path"\s*"([^"]+)"', vdf): libs.add(m.replace("\\\\", "\\"))
    except OSError:
        pass
    for lib in libs:
        p = os.path.join(lib, r"steamapps\common\Sid Meier's Civilization VI")
        if os.path.isdir(p): return p
    raise SystemExit("Civ VI install not found. Set CIV6_ROOT to the game folder (this catalog is optional/inspiration).")

ROOT = find_civ6_root()
OUTMD = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "references", "civ6-policies-governments-catalog.md"))

def clean(t):
    t = html.unescape(t)
    t = re.sub(r'\[ICON_([A-Za-z0-9]+)\]', lambda m: ' '+m.group(1)+' ', t)
    t = re.sub(r'\[[^\]]*\]', '', t)
    t = re.sub(r'\s+', ' ', t).strip()
    t = re.sub(r'\b(\w+)(\s+\1\b)+', r'\1', t, flags=re.I)
    t = re.sub(r'\s+([.,;])', r'\1', t)
    return t.strip()

loc={}
row_re=re.compile(r'<Row\s+Tag="([^"]+)"\s*>(.*?)</Row>', re.S); tx=re.compile(r'<Text>(.*?)</Text>', re.S)
for f in glob.glob(os.path.join(ROOT,"**","Text","en_US","*.xml"), recursive=True):
    try: s=open(f,encoding='utf-8').read()
    except Exception: continue
    for m in row_re.finditer(s):
        t=tx.search(m.group(2))
        if t: loc[m.group(1)]=clean(t.group(1))
L=lambda k: loc.get(k,'') if k else ''
attrs=lambda s: dict(re.findall(r'(\w+)="([^"]*)"', s))
rowrx=re.compile(r'<Row\s+([^>]*?)/?>')
SRC={'Base':'base','Expansion1':'R&F','Expansion2':'GS'}
def src_of(p):
    for k,v in SRC.items():
        if k in p: return v
    return '?'

pfiles=[os.path.join(ROOT,"Base","Assets","Gameplay","Data","Policies.xml"),
        os.path.join(ROOT,"DLC","Expansion1","Data","Expansion1_Policies.xml"),
        os.path.join(ROOT,"DLC","Expansion2","Data","Expansion2_Policies.xml")]
pol={}
for f in pfiles:
    if not os.path.exists(f): continue
    src=src_of(f); s=open(f,encoding='utf-8',errors='ignore').read()
    for m in rowrx.finditer(s):
        a=attrs(m.group(0))
        if 'PolicyType' in a and 'Name' in a:
            pol[a['PolicyType']]={'type':a['PolicyType'],'slot':a.get('GovernmentSlotType','?').replace('SLOT_',''),
                'civic':a.get('PrereqCivic','').replace('CIVIC_',''),'src':src,'name':L(a['Name']),'desc':L(a.get('Description',''))}
pol=list(pol.values())

gfiles=[os.path.join(ROOT,"Base","Assets","Gameplay","Data","Governments.xml"),
        os.path.join(ROOT,"DLC","Expansion1","Data","Expansion1_Governments.xml"),
        os.path.join(ROOT,"DLC","Expansion2","Data","Expansion2_Governments.xml")]
gov={}
for f in gfiles:
    if not os.path.exists(f): continue
    src=src_of(f); s=open(f,encoding='utf-8',errors='ignore').read()
    for m in rowrx.finditer(s):
        a=attrs(m.group(0))
        if 'GovernmentType' in a and 'Name' in a:
            gov[a['GovernmentType']]={'type':a['GovernmentType'],'src':src,'name':L(a['Name']),
                'inherent':L(a.get('InherentBonusDesc','')),'accumbrief':L(a.get('AccumulatedBonusShortDesc','')),
                'accum':L(a.get('AccumulatedBonusDesc',''))}
gov=list(gov.values())

out=[]; w=out.append
w("# Civ VI POLICY CARDS + GOVERNMENTS — INSPIRATION catalog (base + Rise&Fall + Gathering Storm)")
w("\n> Generated by `tools/gen-civ6-cards-catalog.py`. **INSPIRATION only** — mine Civ VI concepts for ideas, but")
w("> **many Civ VI systems don't exist in Civ VII** (Great People/GPP, Governors, Amenities, Housing, Tourism, World")
w("> Congress, chop/harvest, era score…). ALWAYS run an idea through `civ6-civ7-mechanic-delta.md` +")
w("> `effects-collections-catalog.md` before designing it. Civ VI slots: Military / Economic / Diplomatic / Wildcard.\n")
w(f"**Totals:** {len(pol)} policy cards · {len(gov)} governments\n")
by={}
for p in pol: by.setdefault(p['slot'],[]).append(p)
for slot in ['MILITARY','ECONOMIC','DIPLOMATIC','WILDCARD']:
    rows=by.get(slot,[]); w(f"\n## {slot} POLICIES  ({len(rows)})\n"); w("| Policy | Source | Prereq Civic | Effect |"); w("|---|---|---|---|")
    for p in sorted(rows,key=lambda x:x['type']): w(f"| **{p['name']}** `{p['type']}` | {p['src']} | {p['civic']} | {p['desc']} |")
other=[p for p in pol if p['slot'] not in ('MILITARY','ECONOMIC','DIPLOMATIC','WILDCARD')]
if other:
    w(f"\n## OTHER-SLOT POLICIES ({len(other)})\n"); w("| Policy | Slot | Source | Effect |"); w("|---|---|---|---|")
    for p in sorted(other,key=lambda x:x['type']): w(f"| **{p['name']}** | {p['slot']} | {p['src']} | {p['desc']} |")
w(f"\n## GOVERNMENTS  ({len(gov)})\n")
for g in sorted(gov,key=lambda x:x['type']):
    w(f"\n### {g['name']}  (`{g['type']}`, {g['src']})")
    w(f"- **Inherent bonus:** {g['inherent'] or '—'}")
    if g['accumbrief'] or g['accum']: w(f"- **Legacy/accumulated bonus:** {g['accumbrief'] or g['accum']}")

os.makedirs(os.path.dirname(OUTMD), exist_ok=True)
open(OUTMD,"w",encoding="utf-8").write("\n".join(out))
print(f"wrote {OUTMD}\n  policies {len(pol)} | governments {len(gov)} | LOC {len(loc)}")
